-- Caso 1
-- Observando bien vemos que las columnas que necesitamos las obtenemos con 3 tablas,
-- PROFESIONAL, EMPRESA Y ASESORIA

SELECT
    p.ID_PROFESIONAL as ID,
    p.APPATERNO || ' ' || p.APMATERNO || ', ' || p.NOMBRE as PROFESIONAL,
    -- BANCA
    COUNT(CASE WHEN e.COD_SECTOR = 3 THEN 1 END) as NRO_ASESORIA_BANCA,
    TO_CHAR(SUM(CASE WHEN e.COD_SECTOR = 3 THEN a.HONORARIO ELSE 0 END), 'L999G999G999') as MONTO_TOTAL_BANCA,
    -- RETAIL
    COUNT(CASE WHEN e.COD_SECTOR = 4 THEN 1 END) as NRO_ASESORIA_RETAIL,
    TO_CHAR(SUM(CASE WHEN e.COD_SECTOR = 4 THEN a.HONORARIO ELSE 0 END), 'L999G999G999') as MONTO_TOTAL_RETAIL,
    -- BANCA + RETAIL
    COUNT(CASE WHEN e.COD_SECTOR IN (3,4) THEN 1 END) as NRO_ASESORIA_TOTAL,
    TO_CHAR(SUM(CASE WHEN e.COD_SECTOR IN (3,4) THEN a.HONORARIO ELSE 0 END), 'L999G999G999') as TOTAL_HONORARIOS

FROM
    PROFESIONAL p
    JOIN ASESORIA a ON p.ID_PROFESIONAL = a.ID_PROFESIONAL
    JOIN EMPRESA e ON a.COD_EMPRESA = e.COD_EMPRESA

WHERE
    e.COD_SECTOR IN (3,4) -- QUE SEAN DE BANCA O RETAIL

    -- El enunciado dice que debe tener asesorías en ambos sectores por eso usamos INTERSECT
    AND p.ID_PROFESIONAL IN(

        --BANCA
        SELECT ID_PROFESIONAL
        FROM ASESORIA a2
        JOIN EMPRESA e2 ON a2.COD_EMPRESA = e2.COD_EMPRESA
        WHERE e2.COD_SECTOR = 3

        INTERSECT

        --RETAIL
        SELECT ID_PROFESIONAL
        FROM ASESORIA a3
        JOIN EMPRESA e3 ON a3.COD_EMPRESA = e3.COD_EMPRESA
        WHERE e3.COD_SECTOR = 4
    )
GROUP BY
    p.ID_PROFESIONAL,
    p.APPATERNO,
    p.APMATERNO,
    p.NOMBRE

ORDER BY p.ID_PROFESIONAL ASC;



-- Caso 2: Resumen de Honorarios
-- Tablas profesional, Profesion, Comuna, Asesoria

SELECT
    p.ID_PROFESIONAL,
    p.APPATERNO || ' ' || p.APMATERNO || ', ' || p.NOMBRE as NOMBRE_COMPLETO,
    pr.NOMBRE_PROFESION,
    c.NOM_COMUNA,
    COUNT(a.ID_PROFESIONAL) as NRO_ASESORIAS,
    ROUND(SUM(a.HONORARIO)) as MONTO_TOTAL_HONORARIOS,
    ROUND(AVG(a.HONORARIO)) as PROMEDIO_HONORARIOS,
    ROUND(MIN(a.HONORARIO)) as HONORARIO_MINIMO,
    ROUND(MAX(a.HONORARIO)) as HONORARIO_MAXIMO

FROM
    PROFESIONAL p
    JOIN PROFESION pr ON p.COD_PROFESION = pr.COD_PROFESION
    JOIN COMUNA c ON p.COD_COMUNA = c.COD_COMUNA
    JOIN ASESORIA a ON p.ID_PROFESIONAL = a.ID_PROFESIONAL

WHERE
    --extraemos mes de abril
    EXTRACT(MONTH FROM a.FIN_ASESORIA) = 4
    --extraemos año anterior al actual
    AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1

GROUP BY
    p.ID_PROFESIONAL,
    p.APPATERNO,
    p.APMATERNO,
    p.NOMBRE,
    pr.NOMBRE_PROFESION,
    c.NOM_COMUNA
ORDER BY p.ID_PROFESIONAL ASC;

CREATE TABLE REPORTE_MES AS
    SELECT
        p.ID_PROFESIONAL,
        p.APPATERNO || ' ' || p.APMATERNO || ', ' || p.NOMBRE as NOMBRE_COMPLETO,
        pr.NOMBRE_PROFESION,
        c.NOM_COMUNA,
        COUNT(a.ID_PROFESIONAL) as NRO_ASESORIAS,
        ROUND(SUM(a.HONORARIO)) as MONTO_TOTAL_HONORARIOS,
        ROUND(AVG(a.HONORARIO)) as PROMEDIO_HONORARIOS,
        ROUND(MIN(a.HONORARIO)) as HONORARIO_MINIMO,
        ROUND(MAX(a.HONORARIO)) as HONORARIO_MAXIMO

    FROM
        PROFESIONAL p
            JOIN PROFESION pr ON p.COD_PROFESION = pr.COD_PROFESION
            JOIN COMUNA c ON p.COD_COMUNA = c.COD_COMUNA
            JOIN ASESORIA a ON p.ID_PROFESIONAL = a.ID_PROFESIONAL

    WHERE
        EXTRACT(MONTH FROM a.FIN_ASESORIA) = 4
      AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1

    GROUP BY
        p.ID_PROFESIONAL,
        p.APPATERNO,
        p.APMATERNO,
        p.NOMBRE,
        pr.NOMBRE_PROFESION,
        c.NOM_COMUNA
    ORDER BY p.ID_PROFESIONAL ASC;

SELECT * FROM REPORTE_MES;

--Caso 3

--Reporte ANTES de actualizar el sueldo
SELECT
    ROUND(SUM(a.HONORARIO)),
    p.ID_PROFESIONAL,
    p.NUMRUN_PROF,
    p.SUELDO

FROM
    PROFESIONAL p
    JOIN ASESORIA a ON p.ID_PROFESIONAL = a.ID_PROFESIONAL

WHERE
    EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
    AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1

GROUP BY
    p.ID_PROFESIONAL,
    p.NUMRUN_PROF,
    p.SUELDO;

-- Actualización del sueldo
UPDATE PROFESIONAL p
SET SUELDO = ROUND(SUELDO * (
    CASE
        WHEN ( -- cuando los honorarios sean menores a 1.000.000
            SELECT SUM(a.HONORARIO)
            FROM ASESORIA a
            WHERE a.ID_PROFESIONAL = p.ID_PROFESIONAL
              AND EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
              AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
        ) < 1000000 THEN 1.10
        ELSE 1.15
    END

    ),0) --Aqui se cierra el round y el paretesis del set

--Ahora nos aseguramos actualizar solo los profesionales que cumplen la condición
WHERE p.ID_PROFESIONAL IN (
    SELECT a.ID_PROFESIONAL
    FROM ASESORIA a
    WHERE EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
      AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
    GROUP BY a.ID_PROFESIONAL
);

--Reporte DESPUÉS de actualizar el sueldo
SELECT
    ROUND(SUM(a.HONORARIO)),
    p.ID_PROFESIONAL,
    p.NUMRUN_PROF,
    p.SUELDO

FROM
    PROFESIONAL p
        JOIN ASESORIA a ON p.ID_PROFESIONAL = a.ID_PROFESIONAL

WHERE
    EXTRACT(MONTH FROM a.FIN_ASESORIA) = 3
  AND EXTRACT(YEAR FROM a.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1

GROUP BY
    p.ID_PROFESIONAL,
    p.NUMRUN_PROF,
    p.SUELDO;



